
-- SCOTT."BOARD_jsp" definition

CREATE TABLE "SCOTT"."BOARD_jsp"
(	"NUM" NUMBER,
     "TITLE" VARCHAR2(200) NOT NULL ENABLE,
     "CONTENT" VARCHAR2(2000) NOT NULL ENABLE,
     "ID" VARCHAR2(10) NOT NULL ENABLE,
     "POSTDATE" DATE DEFAULT sysdate NOT NULL ENABLE,
     "VISITCOUNT" NUMBER(6,0),
     PRIMARY KEY ("NUM")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008328" ON "SCOTT"."BOARD_jsp" ("NUM")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ;

-- SCOTT.MEMBER_JSP definition

CREATE TABLE "SCOTT"."MEMBER_JSP"
(	"ID" VARCHAR2(10) NOT NULL ENABLE,
     "PASS" VARCHAR2(10) NOT NULL ENABLE,
     "NAME" VARCHAR2(10) NOT NULL ENABLE,
     "date" DATE DEFAULT sysdate NOT NULL ENABLE,
     CONSTRAINT "MEMBER_JSP_UNIQUE" UNIQUE ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."MEMBER_JSP_UNIQUE" ON "SCOTT"."MEMBER_JSP" ("ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "USERS" ;

COMMENT ON COLUMN SCOTT.MEMBER_JSP.ID IS '아이디';
COMMENT ON COLUMN SCOTT.MEMBER_JSP.PASS IS '패스워드';
COMMENT ON COLUMN SCOTT.MEMBER_JSP.NAME IS '이름';
COMMENT ON COLUMN SCOTT.MEMBER_JSP."POSTDATE" IS '가입날짜';

CREATE SEQUENCE seq_board_num
    INCREMENT BY 1 --1씩 증가
    START WITH 1 --1부터 시작
    MINVALUE 1 --최소값 1
<<<<<<< HEAD
    nomaxvalue -- 최대값 무한대(사이클 ㄴㄴ)
=======
    nomaxvalue -- 최대값 무한대(사이클 ㄴㄴ-한정하게 되면 되돌아서 다시 출력되므로)
>>>>>>> d95d19b (001)
nocycle -- 순환
nocache; --캐시 안함