--
-- -- "BOARD_jsp" definition
--
-- CREATE TABLE "SCOTT"."BOARD_jsp"
-- (	"NUM" NUMBER,
--      "TITLE" VARCHAR2(200) NOT NULL ENABLE,
--      "CONTENT" VARCHAR2(2000) NOT NULL ENABLE,
--      "ID" VARCHAR2(10) NOT NULL ENABLE,
--      "POSTDATE" DATE DEFAULT sysdate NOT NULL ENABLE,
--      "VISITCOUNT" NUMBER(6,0),
--      PRIMARY KEY ("NUM")
--          USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
--          TABLESPACE "USERS"  ENABLE
-- ) SEGMENT CREATION DEFERRED
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
--  NOCOMPRESS LOGGING
--   TABLESPACE "USERS" ;
--
-- CREATE UNIQUE INDEX "SCOTT"."SYS_C008328" ON "SCOTT"."BOARD_jsp" ("NUM")
--     PCTFREE 10 INITRANS 2 MAXTRANS 255
--   TABLESPACE "USERS" ;
--
-- -- SCOTT.MEMBER_JSP definition
--
-- CREATE TABLE "SCOTT"."MEMBER_JSP"
-- (	"ID" VARCHAR2(10) NOT NULL ENABLE,
--      "PASS" VARCHAR2(10) NOT NULL ENABLE,
--      "NAME" VARCHAR2(10) NOT NULL ENABLE,
--      "date" DATE DEFAULT sysdate NOT NULL ENABLE,
--      CONSTRAINT "MEMBER_JSP_UNIQUE" UNIQUE ("ID")
--          USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
--          TABLESPACE "USERS"  ENABLE
-- ) SEGMENT CREATION DEFERRED
--   PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
--  NOCOMPRESS LOGGING
--   TABLESPACE "USERS" ;
--
-- CREATE UNIQUE INDEX "SCOTT"."MEMBER_JSP_UNIQUE" ON "SCOTT"."MEMBER_JSP" ("ID")
--     PCTFREE 10 INITRANS 2 MAXTRANS 255
--   TABLESPACE "USERS" ;
--
-- COMMENT ON COLUMN SCOTT.MEMBER_JSP.ID IS '아이디';
-- COMMENT ON COLUMN SCOTT.MEMBER_JSP.PASS IS '패스워드';
-- COMMENT ON COLUMN SCOTT.MEMBER_JSP.NAME IS '이름';
-- COMMENT ON COLUMN SCOTT.MEMBER_JSP."POSTDATE" IS '가입날짜';
--
-- CREATE SEQUENCE seq_board_num
--     INCREMENT BY 1 --1씩 증가
--     START WITH 1 --1부터 시작
--     MINVALUE 1 --최소값 1
--     nomaxvalue -- 최대값 무한대(사이클 ㄴㄴ-한정하게 되면 되돌아서 다시 출력되므로)
--     nocycle -- 순환
--     nocache; --캐시 안함

-- 0207 new
-- SCOTT.BOARD_JSP definition

CREATE TABLE "SCOTT"."BOARD_JSP"
(	"NUM" NUMBER,
     "TITLE" VARCHAR2(200) NOT NULL ENABLE,
     "CONTENT" VARCHAR2(2000) NOT NULL ENABLE,
     "ID" VARCHAR2(10) NOT NULL ENABLE,
     "POSTDATE" DATE DEFAULT sysdate NOT NULL ENABLE,
     "VISITCOUNT" NUMBER(6,0),
     PRIMARY KEY ("NUM")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."SYS_C008334" ON "SCOTT"."BOARD_JSP" ("NUM")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

-- SCOTT.MEMBER_JSP definition

CREATE TABLE "SCOTT"."MEMBER_JSP"
(	"ID" VARCHAR2(10) NOT NULL ENABLE,
     "PASS" VARCHAR2(10) NOT NULL ENABLE,
     "NAME" VARCHAR2(30) NOT NULL ENABLE,
     "REGIDATE" DATE DEFAULT sysdate NOT NULL ENABLE,
     CONSTRAINT "MEMBER_JSP_PK" PRIMARY KEY ("ID")
         USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
         STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
         PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
         BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
         TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "SCOTT"."MEMBER_JSP_PK" ON "SCOTT"."MEMBER_JSP" ("ID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

COMMENT ON COLUMN SCOTT.MEMBER_JSP.ID IS '아이디';
COMMENT ON COLUMN SCOTT.MEMBER_JSP.PASS IS '패스워드';
COMMENT ON COLUMN SCOTT.MEMBER_JSP.NAME IS '이름';
COMMENT ON COLUMN SCOTT.MEMBER_JSP.REGIDATE IS '가입날짜';

CREATE SEQUENCE SCOTT.SEQ_BOARD_NUM INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE NOCACHE NOORDER;